### ISSUE TITLE
Fix cyclic linked list causes stackoverflow in 032_arrlist

### ISSUE THREAD

**Issue by JC626** [Whiley/WyBench#28] opened 2018-07-16 22:04 UTC
In 032_arrlist\main the function `length(...)` fails when a linked list is cyclic (contains a loop).

An input that causes this error:
list = {size:1,links:[{data:0,next:0}]}
i = 0

This is caused by:
```
Link ith = list.links[i]
return 1 + length(list,ith.next)
```

Due to the `ith.next` element in the link pointing to the head, (index 0), so the next recursive call gives the same arguments (as _i_ is 0 again).

**Comment by DavePearce** [comment] 2018-07-17 22:43
Yup, obviously broken.  Merged now.

**Comment by DavePearce** [comment] 2018-07-17 22:47
Ok, this is not a bug in `length()` but actually one in your tool.  Structures (such as `LinkedList` above) cannot be cyclic in Whiley.  If they could be then, yes, the `length()` function would not terminate.  How did your tool spot non-termination though??

**Comment by DavePearce** [comment] 2018-07-17 22:49
Scrap that.  I need to look at the benchmark properly!!  I guess I wrote it, though I don't remember.  The problem is that this was based on a benchmark where I was using a recursive type `LInkedList` which couldn't be cyclic.  But, in the array for, then yes it can.

**Comment by DavePearce** [comment] 2018-07-23 00:05
_(Janice points out by email that my fix for this benchmark is wrong)_

Have now updated the invariant for `LinkedList` to be this:

```property valid(LinkedList l, Link n, int i)
// All next links go "down", cannot be cyclic or a "null"
where (n.next < i) || (i == 0) || (n.next == |l.links|)

type LinkedList is ({Link[] links, nat size} l)
// Never more links than available space
where l.size <= |l.links|
// All links are valid
where all { i in 0 .. l.size | valid(l,l.links[i],i) }
```

I think that works better now.  Unfortunately, there seems to be some problem running debug code.  Specifically, using `ascii::append(string,string)` in certain situations is causing an exception for reasons unknown. Have messed around with the implementation of that method to no avail at this stage.

**Comment by JC626** [comment] 2018-07-25 03:37
Think this issue can be closed now as the cyclic problem has been fixed.

**Closed** 2018-07-25 03:41 UTC

**Comment by DavePearce** [comment] 2018-07-27 03:33
Ok, yup, looks like I screwed up.  The problem was indeed the postcondition in `ascii::append(string,string)`.  Using the recompiled library has fixed that.
